version: 2.1

workflows:
  version: 2
  build:
    jobs: 
      - test
jobs:
  test:
    working_directory: ~/buildertools
    docker:
      - image: cimg/python:3.9.6-node
    steps:
      - checkout
      - run:
          name: update-npm
          command: "sudo npm install -g npm@latest"
      - run:
          name: install-typescript
          command: "sudo npm install -g typescript"
      - run:
          name: download-toolchain
          command: "git clone https://github.com/zheka2304/innercore-mod-toolchain.git ~/toolchain"
      - run:
          name: setup-toolchain
          command: "mv ~/toolchain/toolchain-mod/toolchain ~/buildertools"
      - run:
          name: test
          command: "python ~/buildertools/toolchain/python/task.py clearOutput buildScripts buildResources compileNativeDebug compileJavaDebug buildAdditional buildInfo"
